#! /bin/bash
pandoc --template=GitHub.html5 data/index.md -o index.html --metadata title="Jonathan Fischoff's Personal Site"
pandoc --template=GitHub.html5 data/blog/faster-database-testing.md -o blog/faster-database-testing.html --metadata title='Faster Database Testing with the New `tmp-postgres`'
pandoc --template=GitHub.html5 data/blog/development-notes-12-25-19.md -o blog/development-notes-12-25-19.html --metadata title='Development Notes: Decemember 25th 2019'
pandoc --template=GitHub.html5 data/blog/development-notes-12-26-19.md -o blog/development-notes-12-26-19.html --metadata title='Development Notes: Decemember 26th 2019'
pandoc --template=GitHub.html5 data/blog/development-notes-12-27-19.md -o blog/development-notes-12-27-19.html --metadata title='Development Notes: Decemember 27th 2019'
pandoc --template=GitHub.html5 data/blog/keeping-database-tests-fast.md -o blog/keeping-database-tests-fast.html --metadata title='Keeping Database Tests Fast with `tmp-postgres`'
pandoc --template=GitHub.html5 data/blog/development-notes-12-28-19.md -o blog/development-notes-12-28-19.html --metadata title='Development Notes: Decemember 28th 2019'
pandoc --template=GitHub.html5 data/blog/development-notes-12-29-19.md -o blog/development-notes-12-29-19.html --metadata title='Development Notes: Decemember 29th 2019'
pandoc --template=GitHub.html5 data/blog/development-notes-12-30-19.md -o blog/development-notes-12-30-19.html --metadata title='Development Notes: Decemember 30th 2019'
pandoc --template=GitHub.html5 data/blog/development-notes-12-31-19.md -o blog/development-notes-12-31-19.html --metadata title='Development Notes: Decemember 31th 2019'
pandoc --template=GitHub.html5 data/blog/development-notes-01-01-20.md -o blog/development-notes-01-01-20.html --metadata title='Development Notes: January 1st 2020'
pandoc --template=GitHub.html5 data/blog/development-notes-01-02-20.md -o blog/development-notes-01-02-20.html --metadata title='Development Notes: January 2nd 2020'
pandoc --template=GitHub.html5 data/blog/development-notes-01-03-20.md -o blog/development-notes-01-03-20.html --metadata title='Development Notes: January 3rd 2020'
pandoc --template=GitHub.html5 data/blog/development-notes-01-04-20.md -o blog/development-notes-01-04-20.html --metadata title='Development Notes: January 4th 2020'
pandoc --template=GitHub.html5 data/blog/development-notes-01-05-20.md -o blog/development-notes-01-05-20.html --metadata title='Development Notes: January 5th 2020'
pandoc --template=GitHub.html5 data/blog/development-notes-01-06-20.md -o blog/development-notes-01-06-20.html --metadata title='Development Notes: January 6th 2020'
pandoc --template=GitHub.html5 data/blog/development-notes-01-10-20.md -o blog/development-notes-01-10-20.html --metadata title='Development Notes: January 10th 2020'
pandoc --template=GitHub.html5 data/blog/development-notes-01-11-20.md -o blog/development-notes-01-11-20.html --metadata title='Development Notes: January 11th 2020'
pandoc --template=GitHub.html5 data/blog/when-threadwaitread-doesnt.md -o blog/when-threadwaitread-doesnt.html --metadata title="When threadWaitRead Doesn't"
pandoc --template=GitHub.html5 data/blog/the-eventmanager-and-non-blocking-io.md -o blog/the-eventmanager-and-non-blocking-io.html --metadata title="Non-blocking IO and the EventManager"
pandoc --template=GitHub.html5 data/blog/bitmap-index-scan.md -o blog/bitmap-index-scan.html --metadata title="What to Think When You See a Bitmap Index Scan"
pandoc --template=GitHub.html5 data/blog/introducing-hasql-queue.md -o blog/introducing-hasql-queue.html --metadata title="Introducing hasql-queue"
pandoc --template=GitHub.html5 data/blog/making-nfts-with-plutus.md -o blog/making-nfts-with-plutus.html --metadata title="Making NFTs with Plutus"
